name: Build Image and Test with Snyk

on:
  push:
    branches:
    - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@master

        # - name: Set up QEMU
        #   uses: docker/setup-qemu-action@v3

        # - name: Set up Docker Buildx
        #   uses: docker/setup-buildx-action@v3

        # - name: Login to Docker Hub
        #   uses: docker/login-action@v3
        #   with:
        #     username: a1doll
        #     password: ${{ secrets.DOCKERHUB_TOKEN }}

        # - name: Build and push
        #   uses: docker/build-push-action@v5
        #   with:
        #     push: true
            # tags: a1doll/snyk-juice-shop:linux
